server:
  port: 8084

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cloud:
    nacos:
      config:
        import-check:
          enabled: false
  datasource:
    url: jdbc:mysql://localhost:3306/db_logistics?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        acknowledge-mode: auto

feign:
  sentinel:
    enabled: true

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.logistics.logistics.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

springdoc:
  swagger-ui:
    path: /doc.html

xxl:
  job:
    admin:
      addresses: http://localhost:18088/xxl-job-admin
    executor:
      appname: logistics-executor
      ip: 192.168.1.101
      port: 9999
      logpath: /logs/xxl-job
